"""Node 6 — Deliver: shape generated videos into result variants."""
from __future__ import annotations

from app.graph.state import AgentState


LABEL_MAP = ["Emotional", "Feature-Focused", "Bold & Viral"]


async def deliver_node(state: AgentState) -> dict:
    if state.get("status") == "error":
        return {
            "status": "error",
            "error": state.get("error") or "Video generation failed.",
        }

    video_jobs = state.get("video_jobs", [])
    successful_jobs = [job for job in video_jobs if job.get("video_url")]
    if not successful_jobs:
        failed = sum(1 for job in video_jobs if str(job.get("status", "")).lower() in {"failed", "expired"})
        return {
            "status": "error",
            "error": f"No playable videos were generated by Seedance. Failed/expired jobs: {failed}/{len(video_jobs)}",
        }

    scored_variants = []
    for i, job in enumerate(successful_jobs):
        scored_variants.append({
            "id": f"v{i}",
            "label": LABEL_MAP[i] if i < len(LABEL_MAP) else f"Variant {i+1}",
            "prompt": job.get("prompt", ""),
            "video_url": job.get("video_url", ""),
            "dimensions": [],
            "quality_engagement_score": 0,
        })

    return {
        "scored_variants": scored_variants,
        "status": "delivered",
    }
